storage_path: "mongodb://192.168.0.102:27017/" # адрес для подключения к MongoDB
storage_user: "admin" # пользователь для аутентификации в MongoDB
storage_passwd: "COMMENTS_DB_PASSWD" # пароль для аутентификации в MongoDB
content_length: 1000
http_server:
  address: "localhost:80"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s